services:
  db:
    image: ankane/pgvector
    container_name: pgvector_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: borris
      POSTGRES_DB: deepsearch
    ports:
      - "5431:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
